---
title: "investigate_robustness"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{investigate_robustness}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(funkycells)
```

Investigate summary statistics under the null
```{r, eval=FALSE}
simulateNull <- function(seed=NA){
  ## SET SEED
  if(!is.na(seed)){
    set.seed(seed)
  }
  
  ## SIMULATE SPATIAL
  dat0 <- simulatePP(
    agentVarData =
      data.frame(
        "outcome" = c(0, 1),
        "c1" = c(0, 0),
        "c2" = c(1 / 25, 1 / 25), "c3" = c(1 / 50, 1 / 50),
        "c4" = c(0, 0),
        "c5" = c(0, 0), "c6" = c(0, 0),
        "c7" = c(0, 0), "c8" = c(1 / 100, 1 / 100),
        "c9" = c(1 / 20, 1 / 20), "c10" = c(1 / 250, 1 / 250),
        "c11" = c(1 / 100, 1 / 100), "c12" = c(1 / 80, 1 / 80),
        "c13" = c(0, 0), "c14" = c(0, 0),
        "c15" = c(0, 0), "c16" = c(1 / 10, 1 / 10)
      ),
    agentKappaData = data.frame(
      "agent" = paste0("c", 1:16),
      "clusterAgent" = c(NA, "c1", "c1", rep(NA, 12), "c1"),
      "kappa" = c(
        rbinom(1, 100, 0.5),
        rbinom(1, 100, 0.5),
        rbinom(1, 30, 0.5),
        rbinom(1, 80, 0.5),
        rbinom(1, 350, 0.5),
        rbinom(1, 100, 0.5),
        rbinom(1, 120, 0.5),
        rbinom(1, 150, 0.5),
        rbinom(2, 250, 0.5),
        rbinom(1, 600, 0.5),
        rbinom(1, 60, 0.5),
        rbinom(2, 140, 0.5),
        rbinom(1, 20, 0.5),
        rbinom(1, 5, 0.5)
      )
    ),
    unitsPerOutcome = 15,
    replicatesPerUnit = 1,
    silent = T
  )
  dat1 <- simulatePP(
    agentVarData =
      data.frame(
        "outcome" = c(0, 1),
        "c1" = c(0, 0),
        "c2" = c(1 / 25, 1 / 25), "c3" = c(1 / 50, 1 / 50),
        "c4" = c(0, 0),
        "c5" = c(0, 0), "c6" = c(0, 0),
        "c7" = c(0, 0), "c8" = c(1 / 100, 1 / 100),
        "c9" = c(1 / 20, 1 / 20), "c10" = c(1 / 250, 1 / 250),
        "c11" = c(1 / 100, 1 / 100), "c12" = c(1 / 80, 1 / 80),
        "c13" = c(0, 0), "c14" = c(0, 0),
        "c15" = c(0, 0), "c16" = c(1 / 10, 1 / 10)
      ),
    agentKappaData = data.frame(
      "agent" = paste0("c", 1:16),
      "clusterAgent" = c(NA, "c1", "c1", rep(NA, 12), "c1"),
      "kappa" = c(
        rbinom(1, 100, 0.5),
        rbinom(1, 100, 0.5),
        rbinom(1, 30, 0.5),
        rbinom(1, 80, 0.5),
        rbinom(1, 350, 0.5),
        rbinom(1, 100, 0.5),
        rbinom(1, 120, 0.5),
        rbinom(1, 150, 0.5),
        rbinom(2, 250, 0.5),
        rbinom(1, 600, 0.5),
        rbinom(1, 60, 0.5),
        rbinom(2, 140, 0.5),
        rbinom(1, 20, 0.5),
        rbinom(1, 5, 0.5)
      )
    ),
    unitsPerOutcome = 2,
    replicatesPerUnit = 1,
    silent = T
  )
  dat1$unit <- ifelse(dat1$unit == "u1", "u31",
                      ifelse(dat1$unit == "u2", "u32",
                             ifelse(dat1$unit == "u3", "u33",
                                    ifelse(dat1$unit == "u4", "u34", NA)
                             )
                      )
  )
  dat1$replicate <- ifelse(dat1$replicate == "1", "31",
                           ifelse(dat1$replicate == "2", "32",
                                  ifelse(dat1$replicate == "3", "33",
                                         ifelse(dat1$replicate == "4", "34", NA)
                                  )
                           )
  )
  
  dat <- rbind(dat0, dat1)
  
  ## ADD META
  cells <- paste0("c", 1:16)
  cells_interactions <- rbind(
    data.frame(t(combn(cells, 2))),
    data.frame("X1" = cells, "X2" = cells)
  )
  
  pcaData <- getKsPCAData(
    data = dat, replicate = "replicate",
    agents_df = cells_interactions,
    xRange = c(0, 1), yRange = c(0, 1),
    silent = T
  )
  pcaMeta <- simulateMeta(pcaData,
                          metaInfo = data.frame(
                            "var" = c("age"),
                            "rdist" = c("rnorm"),
                            "outcome_0" = c("25"),
                            "outcome_1" = c("25")
                          )
  )
  
  pcaMeta
}

summaryStatsSim <- function(data, K = 10,
                            outcome = colnames(data)[1],
                            unit = colnames(data)[2],
                            metaNames = NULL,
                            synthetics = 100,
                            alpha = 0.05,
                            silent = FALSE,
                            rGuessSims = 500,
                            subsetPlotSize = 25, nTrees = 500,
                            method = "class") {
  # if (synthetics == 0) warning("No Synthetics given, variables cannot be aligned.")
  # if (synthetics < 0) stop("Number of synthetics must be positive.")
  ## Error checking
  # .checkData(alignmentMethod) ## TODO:: Add something in
  
  ## Generate Synthetics And Connect
  # components <- colnames(data)[!(colnames(data) %in%
  #                                  c(outcome, unit, metaNames))]
  # nPCs <- ifelse(length(components) == 0,
  #                0,
  #                as.numeric(max(sub(".*_PC", "", components)))
  # )
  
  # KFunctions <- .getUnderlyingVariable(components)
  # Get Var and data column alignment
  # underlyingDataAlignedFunctions <- .getUnderlyingVariable(colnames(data),
  #                                                          returnUnique = FALSE
  # )
  # underlyingVars <- unique(underlyingDataAlignedFunctions)
  # underlyingVars <- underlyingVars[!(underlyingVars %in% c(outcome, unit))]
  
  # underlyingNoiseVars <- c(underlyingVars)
  # if (length(KFunctions) > 0) {
  #   underlyingNoiseVars <- c(
  #     underlyingNoiseVars,
  #     paste0("permuteInternal", 1:synthetics, "K_K")
  #   )
  # }
  # if (length(metaNames) > 0) {
  #   underlyingNoiseVars <- c(
  #     underlyingNoiseVars,
  #     as.vector(sapply(metaNames, function(m) {
  #       paste0(paste0("permuteInternal", 1:synthetics), m)
  #     }))
  #   )
  # }
  
  # avgVI <- data.frame("var" = c(underlyingVars))
  # avgVI_full <- data.frame("var" = c(underlyingNoiseVars))
  
  oobAcc <- rep(NA, K)
  groups <- .getFolds(1:nrow(data), K)
  
  # K-Fold Cross-Validation (True Data)
  if (!silent) cat("CV Trials (", K, "): ", sep = "")
  for (i in 1:K) {
    if (!silent) cat(i, ", ", sep = "")
    
    # Do CV without noise for Sd and OOB
    RF <- funkyForest(
      data = data[-groups[[i]], ],
      outcome = outcome,
      unit = unit,
      varImpPlot = FALSE,
      metaNames = c(metaNames),
      nTrees = nTrees, method = method,
    )
    
    # data_merge <- RF$varImportanceData[, c("var", "avgVI")]
    # colnames(data_merge) <- c("var", paste0("avgVIK", i))
    # avgVI <- merge(avgVI, data_merge, by = "var")
    
    oobAcc[i] <- sum(data[groups[[i]], outcome] ==
                       predict_funkyForest(
                         model = RF$model,
                         data_pred = data[groups[[i]], ],
                         type = "pred", data = data
                       )) /
      nrow(data[groups[[i]], ])
    
    # ## Run on all for VI estimate
    # 
    # # Permute Noise but do the functional components together
    # data_full <- .permuteData(
    #   data_base = data, outcome = outcome, unit = unit,
    #   synthetics = synthetics,
    #   KFunctions = KFunctions, metaNames = metaNames,
    #   underlyingDataAlignedFunctions = underlyingDataAlignedFunctions,
    #   nPCs = nPCs, attach.data = TRUE, permute.data = FALSE
    # )
    # 
    # RF_full <- funkyForest(
    #   data = data_full$data,
    #   outcome = outcome,
    #   unit = unit,
    #   varImpPlot = FALSE,
    #   metaNames = data_full$metaNames,
    #   nTrees = nTrees, keepModels = FALSE
    # )
    # 
    # data_merge <- RF_full$varImportanceData[, c("var", "avgVI")]
    # colnames(data_merge) <- c("var", paste0("avgVIK", i))
    # avgVI_full <- merge(avgVI_full, data_merge, by = "var")
  }
  if (!silent) cat("\n")
  
  # ## Permutation
  # avgVI_perm <- data.frame("var" = c(underlyingNoiseVars))
  # 
  # if (!silent) cat("Permutation Trials (", synthetics, "): ", sep = "")
  # for (sim in 1:synthetics) {
  #   if (!silent) cat(sim, ", ", sep = "")
  #   
  #   # Permute but do the functional components together
  #   data_permute <- .permuteData(data, outcome, unit,
  #                                synthetics, KFunctions, metaNames,
  #                                underlyingDataAlignedFunctions, nPCs,
  #                                attach.data = TRUE, permute.data = TRUE
  #   )
  #   
  #   # Get RF and VI
  #   RF <- funkyForest(
  #     data = data_permute$data,
  #     outcome = outcome,
  #     unit = unit,
  #     varImpPlot = FALSE,
  #     metaNames = data_permute$metaNames,
  #     nTrees = nTrees, keepModels = FALSE
  #   )
  #   
  #   data_merge <- RF$varImportanceData[, c("var", "avgVI")]
  #   colnames(data_merge) <- c("var", paste0("avgVIK", sim))
  #   avgVI_perm <- merge(avgVI_perm, data_merge, by = "var")
  # }
  # if (!silent) cat("\n")
  # 
  # 
  # # Summarize Data
  # # data_summ <- .summData(avgVI_full)[, c("var", "est","sd")]
  # 
  # tmp <- as.data.frame(t(sapply(
  #   X = underlyingVars,
  #   FUN = function(var1, alpha, data_vi, KFunctions) {
  #     if (var1 %in% KFunctions) {
  #       tmp <- data.frame(
  #         var1,
  #         t(as.numeric(apply(
  #           X = data_vi[data_vi$var %in% paste0("permuteInternal", 1:100, "K_K"), -1],
  #           MARGIN = 2, FUN = stats::quantile, probs = 1 - alpha
  #         )))
  #       )
  #     } else {
  #       tmp <- data.frame(
  #         var1,
  #         t(as.numeric(apply(
  #           X = data_vi[data_vi$var %in% paste0("permuteInternal", 1:100, var1), -1],
  #           MARGIN = 2, FUN = stats::quantile, probs = 1 - alpha
  #         )))
  #       )
  #     }
  #     tmp
  #   },
  #   alpha = alpha, data_vi = avgVI_full, KFunctions = KFunctions,
  #   USE.NAMES = FALSE, simplify = "matrix"
  # )))
  # for (i in 2:ncol(tmp)) {
  #   tmp[i] <- unlist(tmp[i])
  # }
  # 
  # noiseCO <- max(tmp[-1])
  # 
  # # If value is 0, will jsut take rather than scale
  # tmp1 <- noiseCO / tmp[, -1]
  # tmp1[sapply(tmp1, simplify = "matrix", is.infinite)] <- 1
  # 
  # avgVI_std <- cbind(
  #   "var" = avgVI_full[avgVI_full$var %in% underlyingVars, 1],
  #   avgVI_full[avgVI_full$var %in% underlyingVars, -1] * tmp1
  # )
  # data_summ <- .summData(avgVI_std)
  # 
  # # Add CV SDs (which do not include any noise Vars)
  # tmp <- .summData(avgVI)
  # colnames(tmp)[3] <- "cvSD"
  # data_summ <- merge(
  #   data_summ,
  #   tmp[, c("var", "cvSD")],
  #   all.x = TRUE
  # )
  # 
  # ## Standardize Data
  # # Get Noise cutoff
  # 
  # tmp <- as.data.frame(t(sapply(
  #   X = underlyingVars,
  #   FUN = function(var, alpha, data_vi, KFunctions) {
  #     if (var %in% KFunctions) {
  #       tmp <- data.frame(
  #         var,
  #         t(as.numeric(apply(
  #           X = data_vi[data_vi$var %in% paste0("permuteInternal", 1:100, "K_K"), -1],
  #           MARGIN = 2, FUN = stats::quantile, probs = 1 - alpha
  #         )))
  #       )
  #     } else {
  #       tmp <- data.frame(
  #         var,
  #         t(as.numeric(apply(
  #           X = data_vi[data_vi$var %in% paste0("permuteInternal", 1:100, var), -1],
  #           MARGIN = 2, FUN = stats::quantile, probs = 1 - alpha
  #         )))
  #       )
  #     }
  #     tmp
  #   },
  #   alpha = alpha, data_vi = avgVI_perm, KFunctions = KFunctions,
  #   USE.NAMES = FALSE, simplify = "matrix"
  # )))
  # for (i in 2:ncol(tmp)) {
  #   tmp[i] <- unlist(tmp[i])
  # }
  # 
  # # If value is 0, will just take rather than scale
  # tmp1 <- noiseCO / tmp[, -1]
  # tmp1[sapply(tmp1, simplify = "matrix", is.infinite)] <- 1
  # 
  # avgVI_perm_std <- cbind(
  #   "var" = avgVI_perm[avgVI_perm$var %in% underlyingVars, 1],
  #   avgVI_perm[avgVI_perm$var %in% underlyingVars, -1] * tmp1
  # )
  # data_perm_summ <- .summData(avgVI_perm_std)
  # 
  # 
  # # Get Interpolation cutoff
  # interpolationCO <- apply(
  #   apply(avgVI_perm_std[-1],
  #         MARGIN = 2, FUN = sort,
  #         decreasing = TRUE
  #   ),
  #   MARGIN = 1, FUN = stats::quantile, probs = 1 - alpha
  # )
  
  # Model accuracy estimates
  data_modelAcc <- .computeModelAccuracy(
    oobAcc = oobAcc,
    outcomes = data[, outcome]
  )
  
  
  ## Get plots and organize results
  data_modelAcc
}


nTrials <- 100
results <- data.frame('OOB'=rep(NA,nTrials),
                      'Bias'=NA,
                      'Guess'=NA)

for(i in 1:nTrials){
  cat(paste0(i,', '))
  set.seed(i^2*123+i*123+1)
  data <- simulateNull()
  
  res <- summaryStatsSim(
    data = data,
    outcome = "outcome",
    unit = "unit",
    metaNames = c("age"),
    silent = T
  )
  
  results[i,] <- as.numeric(res)
}

colMeans(results)
apply(results,MARGIN = 2,median)
apply(results,MARGIN = 2,sd)
tmp <- apply(results,MARGIN = 1,function(x){which.max(x)})
table(tmp)/nTrials
```

Investigate summary statistics under the alternative.
```{r, eval=FALSE}
simulateAlt <- function(seed=NA){
  ## SET SEED
  if(!is.na(seed)){
    set.seed(seed)
  }
  
  ## SIMULATE SPATIAL
  dat0 <- simulatePP(
    agentVarData =
      data.frame(
        "outcome" = c(0, 1),
        "c1" = c(0, 0),
        "c2" = c(1 / 25, 1 / 60), "c3" = c(1 / 50, 1 / 10),
        "c4" = c(0, 0),
        "c5" = c(0, 0), "c6" = c(0, 0),
        "c7" = c(0, 0), "c8" = c(1 / 100, 1 / 100),
        "c9" = c(1 / 20, 1 / 20), "c10" = c(1 / 250, 1 / 250),
        "c11" = c(1 / 100, 1 / 100), "c12" = c(1 / 80, 1 / 80),
        "c13" = c(0, 0), "c14" = c(0, 0),
        "c15" = c(0, 0), "c16" = c(1 / 10, 1 / 10)
      ),
    agentKappaData = data.frame(
      "agent" = paste0("c", 1:16),
      "clusterAgent" = c(NA, "c1", "c1", rep(NA, 12), "c1"),
      "kappa" = c(
        rbinom(1, 100, 0.5),
        rbinom(1, 100, 0.5),
        rbinom(1, 30, 0.5),
        rbinom(1, 80, 0.5),
        rbinom(1, 350, 0.5),
        rbinom(1, 100, 0.5),
        rbinom(1, 120, 0.5),
        rbinom(1, 150, 0.5),
        rbinom(2, 250, 0.5),
        rbinom(1, 600, 0.5),
        rbinom(1, 60, 0.5),
        rbinom(2, 140, 0.5),
        rbinom(1, 20, 0.5),
        rbinom(1, 5, 0.5)
      )
    ),
    unitsPerOutcome = 15,
    replicatesPerUnit = 1,
    silent = T
  )
  dat1 <- simulatePP(
    agentVarData =
      data.frame(
        "outcome" = c(0, 1),
        "c1" = c(0, 0),
        "c2" = c(1 / 25, 1 / 25), "c3" = c(1 / 50, 1 / 50),
        "c4" = c(0, 0),
        "c5" = c(0, 0), "c6" = c(0, 0),
        "c7" = c(0, 0), "c8" = c(1 / 100, 1 / 100),
        "c9" = c(1 / 20, 1 / 20), "c10" = c(1 / 250, 1 / 250),
        "c11" = c(1 / 100, 1 / 100), "c12" = c(1 / 80, 1 / 80),
        "c13" = c(0, 0), "c14" = c(0, 0),
        "c15" = c(0, 0), "c16" = c(1 / 10, 1 / 10)
      ),
    agentKappaData = data.frame(
      "agent" = paste0("c", 1:16),
      "clusterAgent" = c(NA, "c1", "c1", rep(NA, 12), "c1"),
      "kappa" = c(
        rbinom(1, 100, 0.5),
        rbinom(1, 100, 0.5),
        rbinom(1, 30, 0.5),
        rbinom(1, 80, 0.5),
        rbinom(1, 350, 0.5),
        rbinom(1, 100, 0.5),
        rbinom(1, 120, 0.5),
        rbinom(1, 150, 0.5),
        rbinom(2, 250, 0.5),
        rbinom(1, 600, 0.5),
        rbinom(1, 60, 0.5),
        rbinom(2, 140, 0.5),
        rbinom(1, 20, 0.5),
        rbinom(1, 5, 0.5)
      )
    ),
    unitsPerOutcome = 2,
    replicatesPerUnit = 1,
    silent = T
  )
  dat1$unit <- ifelse(dat1$unit == "u1", "u31",
                      ifelse(dat1$unit == "u2", "u32",
                             ifelse(dat1$unit == "u3", "u33",
                                    ifelse(dat1$unit == "u4", "u34", NA)
                             )
                      )
  )
  dat1$replicate <- ifelse(dat1$replicate == "1", "31",
                           ifelse(dat1$replicate == "2", "32",
                                  ifelse(dat1$replicate == "3", "33",
                                         ifelse(dat1$replicate == "4", "34", NA)
                                  )
                           )
  )
  dat <- rbind(dat0, dat1)
  
  ## ADD META
  cells <- paste0("c", 1:16)
  cells_interactions <- rbind(
    data.frame(t(combn(cells, 2))),
    data.frame("X1" = cells, "X2" = cells)
  )
  
  pcaData <- getKsPCAData(
    data = dat, replicate = "replicate",
    agents_df = cells_interactions,
    xRange = c(0, 1), yRange = c(0, 1),
    silent = T
  )
  pcaMeta <- simulateMeta(pcaData,
                          metaInfo = data.frame(
                            "var" = c("age"),
                            "rdist" = c("rnorm"),
                            "outcome_0" = c("25"),
                            "outcome_1" = c("27")
                          )
  )
  
  pcaMeta
}

summaryStatsSim <- function(data, K = 10,
                            outcome = colnames(data)[1],
                            unit = colnames(data)[2],
                            metaNames = NULL,
                            synthetics = 100,
                            alpha = 0.05,
                            silent = FALSE,
                            rGuessSims = 500,
                            subsetPlotSize = 25, nTrees = 500,
                            method = "class") {
  # if (synthetics == 0) warning("No Synthetics given, variables cannot be aligned.")
  # if (synthetics < 0) stop("Number of synthetics must be positive.")
  ## Error checking
  # .checkData(alignmentMethod) ## TODO:: Add something in
  
  ## Generate Synthetics And Connect
  # components <- colnames(data)[!(colnames(data) %in%
  #                                  c(outcome, unit, metaNames))]
  # nPCs <- ifelse(length(components) == 0,
  #                0,
  #                as.numeric(max(sub(".*_PC", "", components)))
  # )
  
  # KFunctions <- .getUnderlyingVariable(components)
  # Get Var and data column alignment
  # underlyingDataAlignedFunctions <- .getUnderlyingVariable(colnames(data),
  #                                                          returnUnique = FALSE
  # )
  # underlyingVars <- unique(underlyingDataAlignedFunctions)
  # underlyingVars <- underlyingVars[!(underlyingVars %in% c(outcome, unit))]
  
  # underlyingNoiseVars <- c(underlyingVars)
  # if (length(KFunctions) > 0) {
  #   underlyingNoiseVars <- c(
  #     underlyingNoiseVars,
  #     paste0("permuteInternal", 1:synthetics, "K_K")
  #   )
  # }
  # if (length(metaNames) > 0) {
  #   underlyingNoiseVars <- c(
  #     underlyingNoiseVars,
  #     as.vector(sapply(metaNames, function(m) {
  #       paste0(paste0("permuteInternal", 1:synthetics), m)
  #     }))
  #   )
  # }
  
  # avgVI <- data.frame("var" = c(underlyingVars))
  # avgVI_full <- data.frame("var" = c(underlyingNoiseVars))
  
  oobAcc <- rep(NA, K)
  groups <- .getFolds(1:nrow(data), K)
  
  # K-Fold Cross-Validation (True Data)
  if (!silent) cat("CV Trials (", K, "): ", sep = "")
  for (i in 1:K) {
    if (!silent) cat(i, ", ", sep = "")
    
    # Do CV without noise for Sd and OOB
    RF <- funkyForest(
      data = data[-groups[[i]], ],
      outcome = outcome,
      unit = unit,
      varImpPlot = FALSE,
      metaNames = c(metaNames),
      nTrees = nTrees, method = method,
    )
    
    # data_merge <- RF$varImportanceData[, c("var", "avgVI")]
    # colnames(data_merge) <- c("var", paste0("avgVIK", i))
    # avgVI <- merge(avgVI, data_merge, by = "var")
    
    oobAcc[i] <- sum(data[groups[[i]], outcome] ==
                       predict_funkyForest(
                         model = RF$model,
                         data_pred = data[groups[[i]], ],
                         type = "pred", data = data
                       )) /
      nrow(data[groups[[i]], ])
    
    # ## Run on all for VI estimate
    # 
    # # Permute Noise but do the functional components together
    # data_full <- .permuteData(
    #   data_base = data, outcome = outcome, unit = unit,
    #   synthetics = synthetics,
    #   KFunctions = KFunctions, metaNames = metaNames,
    #   underlyingDataAlignedFunctions = underlyingDataAlignedFunctions,
    #   nPCs = nPCs, attach.data = TRUE, permute.data = FALSE
    # )
    # 
    # RF_full <- funkyForest(
    #   data = data_full$data,
    #   outcome = outcome,
    #   unit = unit,
    #   varImpPlot = FALSE,
    #   metaNames = data_full$metaNames,
    #   nTrees = nTrees, keepModels = FALSE
    # )
    # 
    # data_merge <- RF_full$varImportanceData[, c("var", "avgVI")]
    # colnames(data_merge) <- c("var", paste0("avgVIK", i))
    # avgVI_full <- merge(avgVI_full, data_merge, by = "var")
  }
  if (!silent) cat("\n")
  
  # ## Permutation
  # avgVI_perm <- data.frame("var" = c(underlyingNoiseVars))
  # 
  # if (!silent) cat("Permutation Trials (", synthetics, "): ", sep = "")
  # for (sim in 1:synthetics) {
  #   if (!silent) cat(sim, ", ", sep = "")
  #   
  #   # Permute but do the functional components together
  #   data_permute <- .permuteData(data, outcome, unit,
  #                                synthetics, KFunctions, metaNames,
  #                                underlyingDataAlignedFunctions, nPCs,
  #                                attach.data = TRUE, permute.data = TRUE
  #   )
  #   
  #   # Get RF and VI
  #   RF <- funkyForest(
  #     data = data_permute$data,
  #     outcome = outcome,
  #     unit = unit,
  #     varImpPlot = FALSE,
  #     metaNames = data_permute$metaNames,
  #     nTrees = nTrees, keepModels = FALSE
  #   )
  #   
  #   data_merge <- RF$varImportanceData[, c("var", "avgVI")]
  #   colnames(data_merge) <- c("var", paste0("avgVIK", sim))
  #   avgVI_perm <- merge(avgVI_perm, data_merge, by = "var")
  # }
  # if (!silent) cat("\n")
  # 
  # 
  # # Summarize Data
  # # data_summ <- .summData(avgVI_full)[, c("var", "est","sd")]
  # 
  # tmp <- as.data.frame(t(sapply(
  #   X = underlyingVars,
  #   FUN = function(var1, alpha, data_vi, KFunctions) {
  #     if (var1 %in% KFunctions) {
  #       tmp <- data.frame(
  #         var1,
  #         t(as.numeric(apply(
  #           X = data_vi[data_vi$var %in% paste0("permuteInternal", 1:100, "K_K"), -1],
  #           MARGIN = 2, FUN = stats::quantile, probs = 1 - alpha
  #         )))
  #       )
  #     } else {
  #       tmp <- data.frame(
  #         var1,
  #         t(as.numeric(apply(
  #           X = data_vi[data_vi$var %in% paste0("permuteInternal", 1:100, var1), -1],
  #           MARGIN = 2, FUN = stats::quantile, probs = 1 - alpha
  #         )))
  #       )
  #     }
  #     tmp
  #   },
  #   alpha = alpha, data_vi = avgVI_full, KFunctions = KFunctions,
  #   USE.NAMES = FALSE, simplify = "matrix"
  # )))
  # for (i in 2:ncol(tmp)) {
  #   tmp[i] <- unlist(tmp[i])
  # }
  # 
  # noiseCO <- max(tmp[-1])
  # 
  # # If value is 0, will jsut take rather than scale
  # tmp1 <- noiseCO / tmp[, -1]
  # tmp1[sapply(tmp1, simplify = "matrix", is.infinite)] <- 1
  # 
  # avgVI_std <- cbind(
  #   "var" = avgVI_full[avgVI_full$var %in% underlyingVars, 1],
  #   avgVI_full[avgVI_full$var %in% underlyingVars, -1] * tmp1
  # )
  # data_summ <- .summData(avgVI_std)
  # 
  # # Add CV SDs (which do not include any noise Vars)
  # tmp <- .summData(avgVI)
  # colnames(tmp)[3] <- "cvSD"
  # data_summ <- merge(
  #   data_summ,
  #   tmp[, c("var", "cvSD")],
  #   all.x = TRUE
  # )
  # 
  # ## Standardize Data
  # # Get Noise cutoff
  # 
  # tmp <- as.data.frame(t(sapply(
  #   X = underlyingVars,
  #   FUN = function(var, alpha, data_vi, KFunctions) {
  #     if (var %in% KFunctions) {
  #       tmp <- data.frame(
  #         var,
  #         t(as.numeric(apply(
  #           X = data_vi[data_vi$var %in% paste0("permuteInternal", 1:100, "K_K"), -1],
  #           MARGIN = 2, FUN = stats::quantile, probs = 1 - alpha
  #         )))
  #       )
  #     } else {
  #       tmp <- data.frame(
  #         var,
  #         t(as.numeric(apply(
  #           X = data_vi[data_vi$var %in% paste0("permuteInternal", 1:100, var), -1],
  #           MARGIN = 2, FUN = stats::quantile, probs = 1 - alpha
  #         )))
  #       )
  #     }
  #     tmp
  #   },
  #   alpha = alpha, data_vi = avgVI_perm, KFunctions = KFunctions,
  #   USE.NAMES = FALSE, simplify = "matrix"
  # )))
  # for (i in 2:ncol(tmp)) {
  #   tmp[i] <- unlist(tmp[i])
  # }
  # 
  # # If value is 0, will just take rather than scale
  # tmp1 <- noiseCO / tmp[, -1]
  # tmp1[sapply(tmp1, simplify = "matrix", is.infinite)] <- 1
  # 
  # avgVI_perm_std <- cbind(
  #   "var" = avgVI_perm[avgVI_perm$var %in% underlyingVars, 1],
  #   avgVI_perm[avgVI_perm$var %in% underlyingVars, -1] * tmp1
  # )
  # data_perm_summ <- .summData(avgVI_perm_std)
  # 
  # 
  # # Get Interpolation cutoff
  # interpolationCO <- apply(
  #   apply(avgVI_perm_std[-1],
  #         MARGIN = 2, FUN = sort,
  #         decreasing = TRUE
  #   ),
  #   MARGIN = 1, FUN = stats::quantile, probs = 1 - alpha
  # )
  
  # Model accuracy estimates
  data_modelAcc <- .computeModelAccuracy(
    oobAcc = oobAcc,
    outcomes = data[, outcome]
  )
  
  
  ## Get plots and organize results
  data_modelAcc
}


nTrials <- 100
results <- data.frame('OOB'=rep(NA,nTrials),
                      'Bias'=NA,
                      'Guess'=NA)

for(i in 1:nTrials){
  cat(paste0(i,', '))
  set.seed(i^2*123+i*123+123)
  data <- simulateAlt()
  
  res <- summaryStatsSim(
    data = data,
    outcome = "outcome",
    unit = "unit",
    metaNames = c("age"),
    silent = T
  )
  
  results[i,] <- as.numeric(res)
}

colMeans(results)
apply(results,MARGIN = 2,median)
apply(results,MARGIN = 2,sd)
tmp <- apply(results,MARGIN = 1,function(x){which.max(x)})
table(tmp)/nTrials
```



4 cell data simulations for $B$ investigations
```{r, eval=FALSE}
simulateAlt_1int_sm <- function(seed=NA){
  ## SET SEED
  if(!is.na(seed)){
    set.seed(seed)
  }
  
  ## SIMULATE SPATIAL
  dat <- simulatePP(
    agentVarData =
      data.frame(
        "outcome" = c(0, 1),
        "c1" = c(0, 0),
        "c2" = c(1 / 25, 1 / 60),#c(baseline, changes[c])^2,
        "c3" = c(1 / 50, 1 / 50),
        "c4" = c(1 / 10, 1 / 10)
      ),
    agentKappaData = data.frame(
      "agent" = paste0("c", 1:4),
      "clusterAgent" = c(NA, NA, NA, NA),
      "kappa" = c(
        20, 20, 20, 20
      )
    ),
    unitsPerOutcome = 17,
    replicatesPerUnit = 1,
    silent = T
  )
  pcaData <- getKsPCAData(
    data = dat, replicate = "replicate",
    xRange = c(0, 1), yRange = c(0, 1),
    agents_df = cells_interactions,
    silent = TRUE
  )
  pcaMeta <- simulateMeta(pcaData,
                          metaInfo = data.frame(
                            "var" = c("age"),
                            "rdist" = c("rnorm"),
                            "outcome_0" = c("25"),
                            "outcome_1" = c("25")
                          )
  )
  
  pcaMeta
}

nSynths <- c(25,50,100,250,500)
nTrials <- 100

cells <- paste0("c", 1:4)
cells_interactions <- rbind(
  data.frame(t(combn(cells, 2))),
  data.frame("X1" = cells, "X2" = cells)
)


for(i in 1:nTrials){
  cat(paste0(i,', '))
  
  set.seed(i*123)
  data <- simulateAlt_1int_sm()
  
  results <- list()
  results[c(1:length(nSynths))] <-
    list(data.frame(
      'var'= c(paste0(cells_interactions$X1,'_',cells_interactions$X2),
               'age'),
      'noise'=0, 'int'=0, 'both'=0))
  
  for(syn_idx in 1:length(nSynths)){
    
    res <- funkyModel(
      data = data,
      outcome = "outcome",
      unit = "unit",
      synthetics = c(nSynths[syn_idx], 100),
      metaNames = c("age"),
      silent = T
    )
    
    tmp_df <- res$VariableImportance
    tmp_df <- tmp_df[order(-tmp_df$est),]
    results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$NoiseCutoff,'var'],"noise"] <-
      results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$NoiseCutoff,'var'],"noise"] + 1
    results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$InterpolationCutoff,'var'],"int"] <-
      results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$InterpolationCutoff,'var'],"int"] + 1
    results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$InterpolationCutoff &
                                                          tmp_df$est > res$NoiseCutoff ,'var'],"both"] <-
      results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$InterpolationCutoff &
                                                            tmp_df$est > res$NoiseCutoff ,'var'],"both"] + 1
  }
  
  # saveRDS(results, paste0('C:/Users/j53vande/Downloads/funkycells-dev/small_above_mult',i,'.rds'))
  # saveRDS(data, paste0('C:/Users/j53vande/Downloads/funkycells-dev/small_above_mult_data',i,'.rds'))
}  

```

4 cell plots
```{r, eval=FALSE}
## USED
# Load in results
results_list <- list()

for (i in 1:50){
  results_list[[i]] <- readRDS(paste0('C:/Users/j53vande/Downloads/funkycells-dev/small_above_mult',i,'.rds'))
}


# Get combined
nSynths <- c(25,50,100,250,500)

results_combined <- data.frame()
for (i in 1:length(nSynths)){
  results_tmp <- results_list[[1]][[i]]
  for(j in 2:50){
    results_tmp$noise <- results_tmp$noise + results_list[[j]][[i]]$noise
    results_tmp$int <- results_tmp$int + results_list[[j]][[i]]$int
    results_tmp$both <- results_tmp$both + results_list[[j]][[i]]$both
  }
  results_tmp$nSynths <- nSynths[i]
  
  results_combined <- rbind(results_combined,results_tmp)
}

# Take Averages
#   c2_c2 is only real
results_summary <- data.frame()
for(i in 1:length(nSynths)){
  results_summary <- rbind(results_summary,
                           results_combined[results_combined$var=='c2_c2' &
                                              results_combined$nSynths==nSynths[i],])
  results_tmp <- colMeans(results_combined[results_combined$var!='c2_c2' &
                                             results_combined$nSynths==nSynths[i],-1])
  results_tmp <- data.frame('var'='other',
                            'noise'=as.numeric(results_tmp[1]),
                            'int'=as.numeric(results_tmp[2]),
                            'both'=as.numeric(results_tmp[3]),
                            'nSynths'=results_tmp[4])
  results_summary <- rbind(results_summary,
                           results_tmp)
}
rownames(results_summary) <- NULL

# Plot
library(ggplot2)
library(tidyverse)

results_summary1 <- results_summary
results_summary1$var <- ifelse(results_summary1$var=='c2_c2','Effect','No Effect')
results_plot <- results_summary1[,-3] %>% pivot_longer(cols=noise:both)
results_plot$group <- ifelse(results_plot$name=='both',
                             ifelse(results_plot$var=='Effect',
                                    'Both Cutoffs (Effect)',
                                    'Both Cutoffs (No Effect)'),
                             ifelse(results_plot$var=='Effect',
                                    'Noise Cutoff (Effect)',
                                    'Noise Cutoff (No Effect)'))
cols <- scales::hue_pal()(2)

ggplot(results_plot) +
  geom_hline(aes(yintercept=0.05),linetype='dotted',linewidth=2) +
  geom_line(aes(x=nSynths,y=value/50,group=group,color=group,linetype=group),linewidth=2) +
  geom_point(aes(x=nSynths,y=value/50,group=group,color=group),size=3) +
  ggplot2::theme_bw() +
  ggplot2::theme(
    axis.text = ggplot2::element_text(size = 18),
    axis.ticks.y = ggplot2::element_blank(),
    panel.grid.major.y = ggplot2::element_blank(),
    axis.title = ggplot2::element_text(size = 22),
    legend.text = ggplot2::element_text(size=18),
    legend.key.size=unit(2,"lines")
  ) +
  ylab('Percent of Detection') +
  xlab('Number of Synthetics (B)') +
  labs(color = NULL, linetype = NULL) +
  scale_color_manual(values=c(cols[1],cols[2],cols[1],cols[2])) +
  scale_linetype_manual(values=c('solid','solid','dashed','dashed')) +
  guides(color = guide_legend(
    override.aes = list(linetype = c("solid", "solid", "dotted", "dotted")))) +
  ggplot2::theme(
    legend.position = c(0.05,0.75), # top left position
    legend.justification = c(0.05, 0.95), # top left justification
    legend.box.margin = ggplot2::margin(5, l = 5, unit = "mm") # small margin
  ) + 
  ylim(c(0,0.65))



# ggplot(results_summary1)+
#   #geom_line(aes(x=nSynths,y=int/50,group=var,color=var))+
#   geom_line(aes(x=nSynths,y=noise/50,group=var,color=var,linetype='Above Noise'),linewidth=2)+
#   geom_line(aes(x=nSynths,y=both/50,group=var,color=var,linetype='Above Both'),linewidth=2)+
#   geom_point(aes(x=nSynths,y=noise/50,group=var,color=var),size=3)+
#   geom_point(aes(x=nSynths,y=both/50,group=var,color=var),size=3)+
#   #geom_point() +
#   ggplot2::theme_bw() +
#   ggplot2::theme(
#     axis.text = ggplot2::element_text(size = 14),
#     axis.ticks.y = ggplot2::element_blank(),
#     panel.grid.major.y = ggplot2::element_blank(),
#     axis.title = ggplot2::element_text(size = 20)
#   ) +
#   geom_hline(aes(yintercept=0.05),linetype='dotted') +
#   ylab('Percent of Detections (50 Trials)') +
#   xlab('Number of Synthetics (B)')


```


16 cell data simulations for $B$ investigations
```{r, eval=FALSE}
# OLD WAY (PUBLISH)
simulateAlt_1int_sm <- function(seed=NA){
  ## SET SEED
  if(!is.na(seed)){
    set.seed(seed)
  }

  ## SIMULATE SPATIAL
  dat <- simulatePP(
    agentVarData =
      data.frame(
        "outcome" = c(0, 1),
        "c1" = c(0, 0),
        "c2" = c(1 / 25, 1 / 60),#c(baseline, changes[c])^2,
        "c3" = c(1 / 50, 1 / 50),
        "c4" = c(0, 0), "c5" = c(0, 0), "c6" = c(0, 0),
        "c7" = c(0, 0), "c8" = c(0, 0), "c9" = c(0, 0),
        "c10" = c(0, 0), "c11" = c(0, 0), "c12" = c(1 / 30, 1 / 30)^2,
        "c13" = c(0, 0), "c14" = c(1 / 50, 1 / 50)^2,
        "c15" = c(1 / 100, 1 / 100)^2, "c16" = c(1 / 10, 1 / 10)
      ),
    agentKappaData = data.frame(
      "agent" = paste0("c", 1:16),
      "clusterAgent" = rep(NA, 16),
      "kappa" = rep(20, 16)
    ),
    unitsPerOutcome = 17,
    replicatesPerUnit = 1,
    silent = T
  )
  pcaData <- getKsPCAData(
    data = dat, replicate = "replicate",
    xRange = c(0, 1), yRange = c(0, 1),
    agents_df = cells_interactions,
    silent = TRUE
  )
  pcaMeta <- simulateMeta(pcaData,
                          metaInfo = data.frame(
                            "var" = c("age"),
                            "rdist" = c("rnorm"),
                            "outcome_0" = c("25"),
                            "outcome_1" = c("25")
                          )
  )

  pcaMeta
}

nSynths <- c(25,50,100,250,500)
nTrials <- 100

cells <- paste0("c", 1:16)
cells_interactions <- rbind(
  data.frame(t(combn(cells, 2))),
  data.frame("X1" = cells, "X2" = cells)
)

results <- list()
results[c(1:length(nSynths))] <-
  list(data.frame(
    'var'= c(paste0(cells_interactions$X1,'_',cells_interactions$X2),
             'age'),
    'noise'=0, 'int'=0, 'both'=0))
results_list <- data <- list()

for(i in 1:10){#nTrials){
  cat(paste0(i,', '))

  set.seed(i*123)
  data[[i]] <- simulateAlt_1int_sm()

  for(syn_idx in 1:length(nSynths)){

    res <- funkyModel(
      data = data[[i]],
      outcome = "outcome",
      unit = "unit",
      synthetics = c(nSynths[syn_idx], 100),
      metaNames = c("age"),
      silent = T
    )

    tmp_df <- res$VariableImportance
    tmp_df <- tmp_df[order(-tmp_df$est),]
    results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$NoiseCutoff,'var'],"noise"] <-
      results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$NoiseCutoff,'var'],"noise"] + 1
    results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$InterpolationCutoff,'var'],"int"] <-
      results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$InterpolationCutoff,'var'],"int"] + 1
    results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$InterpolationCutoff &
                                                          tmp_df$est > res$NoiseCutoff ,'var'],"both"] <-
      results[[syn_idx]][results[[syn_idx]]$var%in%tmp_df[tmp_df$est > res$InterpolationCutoff &
                                                            tmp_df$est > res$NoiseCutoff ,'var'],"both"] + 1
  }

  # saveRDS(results, 'C:/Users/j53vande/Downloads/funkycells-dev/large_above_mult.rds')
}

```

16 cell plots
```{r, eval=FALSE}
## USED
# Load in results
results_list <- list()
results_list[[1]] <- readRDS('C:/Users/j53vande/Downloads/funkycells-dev/old/large_above_mult.rds')

for (i in 1:4){
  results_list[[i+1]] <- readRDS(paste0('C:/Users/j53vande/Downloads/funkycells-dev/old/large_above_mult',i,'.rds'))
}


# Get combined
nSynths <- c(25,50,100,250,500)

results_combined <- data.frame()
for (i in 1:length(nSynths)){
  results_tmp <- results_list[[1]][[i]]
  for(j in 1:4){
    results_tmp$noise <- results_tmp$noise + results_list[[j+1]][[i]]$noise
    results_tmp$int <- results_tmp$int + results_list[[j+1]][[i]]$int
    results_tmp$both <- results_tmp$both + results_list[[j+1]][[i]]$both
  }
  results_tmp$nSynths <- nSynths[i]
  
  results_combined <- rbind(results_combined,results_tmp)
}

# Take Averages
#   c2_c2 is only real
results_summary <- data.frame()
for(i in 1:length(nSynths)){
  results_summary <- rbind(results_summary,
                           results_combined[results_combined$var=='c2_c2' &
                                              results_combined$nSynths==nSynths[i],])
  results_tmp <- colMeans(results_combined[results_combined$var!='c2_c2' &
                                             results_combined$nSynths==nSynths[i],-1])
  results_tmp <- data.frame('var'='other',
                            'noise'=as.numeric(results_tmp[1]),
                            'int'=as.numeric(results_tmp[2]),
                            'both'=as.numeric(results_tmp[3]),
                            'nSynths'=results_tmp[4])
  results_summary <- rbind(results_summary,
                           results_tmp)
}
rownames(results_summary) <- NULL

# Plot
library(ggplot2)
library(tidyverse)

results_summary1 <- results_summary
results_summary1$var <- ifelse(results_summary1$var=='c2_c2','Effect','No Effect')
results_plot <- results_summary1[,-3] %>% pivot_longer(cols=noise:both)
results_plot$group <- ifelse(results_plot$name=='both',
                             ifelse(results_plot$var=='Effect',
                                    'Both Cutoffs (Effect)',
                                    'Both Cutoffs (No Effect)'),
                             ifelse(results_plot$var=='Effect',
                                    'Noise Cutoff (Effect)',
                                    'Noise Cutoff (No Effect)'))
cols <- scales::hue_pal()(2)

ggplot(results_plot) +
  geom_hline(aes(yintercept=0.05),linetype='dotted',linewidth=2) +
  geom_line(aes(x=nSynths,y=value/50,group=group,color=group,linetype=group),linewidth=2) +
  geom_point(aes(x=nSynths,y=value/50,group=group,color=group),size=3) +
  ggplot2::theme_bw() +
  ggplot2::theme(
    axis.text = ggplot2::element_text(size = 18),
    axis.ticks.y = ggplot2::element_blank(),
    panel.grid.major.y = ggplot2::element_blank(),
    axis.title = ggplot2::element_text(size = 22),
    legend.text = ggplot2::element_text(size=18),
    legend.key.size=unit(2,"lines")
  ) +
  ylab('Percent of Detection') +
  xlab('Number of Synthetics (B)') +
  labs(color = NULL, linetype = NULL) +
  scale_color_manual(values=c(cols[1],cols[2],cols[1],cols[2])) +
  scale_linetype_manual(values=c('solid','solid','dashed','dashed')) +
  guides(color = guide_legend(
    override.aes = list(linetype = c("solid", "solid", "dotted", "dotted")))) +
  ggplot2::theme(
    legend.position = c(0.05,0.75), # top left position
    legend.justification = c(0.05, 0.95), # top left justification
    legend.box.margin = ggplot2::margin(5, l = 5, unit = "mm") # small margin
  ) + 
  ylim(c(0,0.65))


```
